### ISSUE TITLE
Shuffle Deck

### ISSUE THREAD

**Issue by sammysamx20** [cs361fall2017/team33#2]
Sam Young will be doing this implementation. This will be done in a day roughly. It was finished on 10/11/17. This will mostly be using the random function library from one of the java libraries.

**Comment by sammysamx20** [comment]
Seems to be implemented correctly I have a test commented out that shuffles the text based version. 
-sam

**Comment by Bradford-Wong** [comment]
Just tested it and it seems to work as intended. Exceptional job.
