### ISSUE TITLE
Adding Error boxes for Feature Backlogging and Refactoring

### ISSUE THREAD

**Issue by sammysamx20** [cs361fall2017/team33#30]
I might miss a few errors due to not knowing the game. LMK if there is something gone.

**Comment by sammysamx20** [comment]
Turns out i had to refactor as well so I made an Error.Java class to hold the error box since no other class
 has that function type

**Comment by Bradford-Wong** [comment]
Look good. My main suggestion would be to add more rules like the check for when the user tries to add a card that isn't an ace (the new rule).

**Comment by sammysamx20** [comment]
Seems like we both worked on that! I added some error checks with text boxes as well with moving cards in general and the new mode where only aces move. I now want to add error boxes with the remove cards when a user can't remove certain cards.

**Comment by sammysamx20** [comment]
The only thing I changed really from the UML Diagram was adding an error box class object. I did this simply for ease so we can use this class in every other java file. I hope this doesn't dock any thing for points wise.
