### ISSUE TITLE
Deal

### ISSUE THREAD

**Issue by Bradford-Wong** [cs361fall2017/team33#5]
Still working on it.

**Comment by sammysamx20** [comment]
Yeah it seems to work. As I commented on your pull request that I hope it would work with my shuffle function as these two pictures shows two different results!

![949a8470101a4d0f496ed5e47f1dc9a4](https://user-images.githubusercontent.com/25073461/31538062-360e1cac-afb9-11e7-8468-e7e7bfe2b660.png)
![8963b6572c964379eca9d98303aad971](https://user-images.githubusercontent.com/25073461/31538061-33926ee2-afb9-11e7-996e-8f903e8322b3.png)
