### ISSUE TITLE
Remove Cards

### ISSUE THREAD

**Issue by sammysamx20** [cs361fall2017/team33#7]
Austin Sanders will be doing this.

**Comment by sammysamx20** [comment]
Just like I said in the pull request there seems to be no issues yet. However, we might need to add an error checker later as we code some more because removing from an array may cause a "segmentation fault" or whatever it's called in Java.

**Comment by sanderau** [comment]
I think Java's arraylist deals with all the memory allocation in the language and you can't segfault like with C's malloc. However error checking is never a bad idea. When you try to remove from a column that contains nothing the program does not break.
